In [1]:
import pandas as pd

In [3]:
sier_df = pd.read_csv("../data/sierraleone-bumbuna.csv")
sier_df

In [5]:
#renaming important columns to avoid confusion 
rename_col = {'GHI': 'global_horizontal_irradiance', 'DNI': 'direct_normal_irradiance', 'DHI': 'diffuse_horizontal_irradiance', 'Tamb': 'ambient_temperature','RH': 'relative_humidity', 'WS': 'wind_speed', 'WD': 'wind_direction', 'TModA':'temp_module_A', 'TModB': 'temp_module_B'}

In [7]:
sier_df = sier_df.rename(columns = rename_col)
#inspecting result
sier_df.head()

,Timestamp,global_horizontal_irradiance,direct_normal_irradiance,diffuse_horizontal_irradiance,ModA,ModB,ambient_temperature,relative_humidity,wind_speed,WSgust,WSstdev,wind_direction,WDstdev,BP,Cleaning,Precipitation,temp_module_A,temp_module_B,Comments
0,2021-10-30 00:01,-0.7,-0.1,-0.8,0.0,0.0,21.9,99.1,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.3,22.6,NaN
1,2021-10-30 00:02,-0.7,-0.1,-0.8,0.0,0.0,21.9,99.2,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.3,22.6,NaN
2,2021-10-30 00:03,-0.7,-0.1,-0.8,0.0,0.0,21.9,99.2,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.3,22.6,NaN
3,2021-10-30 00:04,-0.7,0.0,-0.8,0.0,0.0,21.9,99.3,0.0,0.0,0.0,0.0,0.0,1002,0,0.1,22.3,22.6,NaN
4,2021-10-30 00:05,-0.7,-0.1,-0.8,0.0,0.0,21.9,99.3,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.3,22.6,NaN

In [8]:
sier_df.shape

(525600, 19)

In [9]:
sier_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525600 entries, 0 to 525599
Data columns (total 19 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Timestamp                      525600 non-null  object
 1   global_horizontal_irradiance   525600 non-null  float64
 2   direct_normal_irradiance       525600 non-null  float64
 3   diffuse_horizontal_irradiance  525600 non-null  float64
 4   ModA                           525600 non-null  float64
 5   ModB                           525600 non-null  float64
 6   ambient_temperature            525600 non-null  float64
 7   relative_humidity              525600 non-null  float64
 8   wind_speed                     525600 non-null  float64
 9   WSgust                         525600 non-null  float64
 10  WSstdev                        525600 non-null  float64
 11  wind_direction                 525600 non-null  float64
 12  WDstdev                        525600 non-null  float64
 13  BP                             525600 non-null  int64
 14  Cleaning                       525600 non-null  int64
 15  Precipitation                  525600 non-null  float64
 16  temp_module_A                  525600 non-null  float64
 17  temp_module_B                  525600 non-null  float64
 18  Comments                       0 non-null       float64
dtypes: float64(16), int64(2), object(1)
memory usage: 76.2+ MB

In [10]:
sier_df = sier_df.drop_duplicates()
sier_df.count()

Timestamp                        525600
global_horizontal_irradiance     525600
direct_normal_irradiance         525600
diffuse_horizontal_irradiance    525600
ModA                             525600
ModB                             525600
ambient_temperature              525600
relative_humidity                525600
wind_speed                       525600
WSgust                           525600
WSstdev                          525600
wind_direction                   525600
WDstdev                          525600
BP                               525600
Cleaning                         525600
Precipitation                    525600
temp_module_A                    525600
temp_module_B                    525600
Comments                              0
dtype: int64

In [11]:
#droping column Comments 
sier_df = sier_df.drop(['Comments'], axis=1)

In [13]:
#cleaning negative values I have used 0 to replace the value
sier_df['global_horizontal_irradiance'] = sier_df['global_horizontal_irradiance'].apply(lambda ghi: 0 if ghi < 0 else ghi)
sier_df['diffuse_horizontal_irradiance'] = sier_df['diffuse_horizontal_irradiance'].apply(lambda dhi: 0 if dhi < 0 else dhi)
sier_df['direct_normal_irradiance'] = sier_df['direct_normal_irradiance'].apply(lambda dni: 0 if dni < 0 else dni)

In [15]:
#checking the cleand data
sier_df.sample(10)

,Timestamp,global_horizontal_irradiance,direct_normal_irradiance,diffuse_horizontal_irradiance,ModA,ModB,ambient_temperature,relative_humidity,wind_speed,WSgust,WSstdev,wind_direction,WDstdev,BP,Cleaning,Precipitation,temp_module_A,temp_module_B
267674,2022-05-03 21:15,0.0,0.0,0.0,0.0,0.0,28.9,73.2,1.7,2.1,0.4,35.8,9.6,999,0,0.0,28.4,28.7
280827,2022-05-13 00:28,0.0,0.0,0.0,0.0,0.0,24.2,96.2,0.8,1.4,0.6,158.8,12.0,1002,0,0.0,24.2,24.5
40633,2021-11-27 05:14,0.0,0.0,0.0,0.0,0.0,23.3,99.1,0.0,0.0,0.0,0.0,0.0,999,0,0.0,23.4,23.8
485655,2022-10-02 06:16,0.0,0.0,0.0,0.0,0.0,20.9,100.0,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,20.5,20.9
145182,2022-02-07 19:43,0.0,0.0,0.0,0.0,0.0,27.5,63.7,0.0,0.0,0.0,0.0,0.0,998,0,0.0,26.5,26.9
97228,2022-01-05 12:29,766.4,634.5,222.7,874.1,840.0,32.5,47.2,1.6,1.9,0.4,281.6,15.6,999,0,0.0,62.1,59.3
159076,2022-02-17 11:17,293.9,14.0,282.7,318.9,292.7,30.6,60.7,2.3,3.1,0.5,18.7,15.2,1000,0,0.0,51.1,46.5
119387,2022-01-20 21:48,0.0,0.0,0.0,0.0,0.0,20.3,67.8,0.7,1.1,0.5,225.2,0.5,1001,0,0.0,18.5,18.8
128730,2022-01-27 09:31,348.6,378.1,152.3,410.7,363.5,24.6,76.2,0.0,0.0,0.0,0.0,0.0,1001,0,0.0,39.6,37.4
289490,2022-05-19 00:51,0.0,0.0,0.0,0.0,0.0,23.9,98.4,0.0,0.0,0.0,0.0,0.0,1000,0,0.0,23.5,23.9

# Statistical Analysis

In [16]:
sier_df.describe()

,global_horizontal_irradiance,direct_normal_irradiance,diffuse_horizontal_irradiance,ModA,ModB,ambient_temperature,relative_humidity,wind_speed,WSgust,WSstdev,wind_direction,WDstdev,BP,Cleaning,Precipitation,temp_module_A,temp_module_B
count,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000
mean,204.406778,116.523731,116.273677,206.643095,198.114691,26.319394,79.448857,1.146113,1.691606,0.363823,133.044668,7.172220,999.876469,0.000967,0.004806,32.504263,32.593091
std,296.787520,218.573992,157.020868,300.896893,288.889073,4.398605,20.520775,1.239248,1.617053,0.295000,114.284792,7.535093,2.104419,0.031074,0.047556,12.434899,12.009161
min,0.000000,0.000000,0.000000,0.000000,0.000000,12.300000,9.900000,0.000000,0.000000,0.000000,0.000000,0.000000,993.000000,0.000000,0.000000,10.700000,11.100000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,23.100000,68.700000,0.000000,0.000000,0.000000,0.000000,0.000000,999.000000,0.000000,0.000000,23.500000,23.800000
50%,0.300000,0.000000,0.000000,3.600000,3.400000,25.300000,85.400000,0.800000,1.600000,0.400000,161.500000,6.200000,1000.000000,0.000000,0.000000,26.600000,26.900000
75%,362.400000,107.000000,224.700000,359.500000,345.400000,29.400000,96.700000,2.000000,2.600000,0.600000,234.100000,12.000000,1001.000000,0.000000,0.000000,40.900000,41.300000
max,1499.000000,946.000000,892.000000,1507.000000,1473.000000,39.900000,100.000000,19.200000,23.900000,4.100000,360.000000,98.400000,1006.000000,1.000000,2.400000,72.800000,70.400000

In [17]:
sier_df['Timestamp'] = pd.to_datetime(sier_df['Timestamp']) # changing to dattime format
daily_mean = sier_df.resample('D', on='Timestamp').mean()
daily_mean.reset_index(inplace=True)
daily_mean

,Timestamp,global_horizontal_irradiance,direct_normal_irradiance,diffuse_horizontal_irradiance,ModA,ModB,ambient_temperature,relative_humidity,wind_speed,WSgust,WSstdev,wind_direction,WDstdev,BP,Cleaning,Precipitation,temp_module_A,temp_module_B
0,2021-10-30,199.691661,86.033843,126.066921,208.919249,203.622307,24.696664,90.128700,1.067616,1.621404,0.386588,143.199722,6.555594,1001.940236,0.001390,0.007575,32.103127,31.751077
1,2021-10-31,250.913889,193.355625,107.144792,266.132431,259.894375,25.060486,88.381250,1.233125,1.820625,0.394514,161.410556,7.561319,1002.070139,0.001389,0.012083,34.134722,34.037222
2,2021-11-01,224.833403,129.656667,127.354097,236.929097,230.410139,25.764444,89.155000,0.837917,1.273472,0.308958,128.590972,5.907569,1002.413889,0.001389,0.010069,34.274792,34.052500
3,2021-11-02,199.955417,146.448125,99.431875,209.162708,205.090139,25.512917,87.105486,0.991736,1.518819,0.373056,135.920139,6.519236,1001.556250,0.002083,0.003056,33.230208,33.067153
4,2021-11-03,246.279861,187.197708,109.149167,259.274167,253.628472,26.172222,86.483194,0.861250,1.308056,0.315139,127.335069,6.043819,1000.295833,0.001389,0.000556,35.290069,35.036250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2022-10-26,247.974514,172.167014,119.081181,256.695625,250.763750,27.348958,88.048611,0.694583,1.050694,0.254028,110.536389,4.938819,998.787500,0.000000,0.000000,35.619514,36.262639
362,2022-10-27,104.202847,9.559514,95.803056,104.607361,101.552917,25.924583,93.395208,0.631111,1.021944,0.264931,105.780625,4.293611,1000.252083,0.001389,0.000000,29.362500,29.701181
363,2022-10-28,185.844792,62.916319,136.726667,191.068889,185.672708,25.522361,91.224444,0.855347,1.275833,0.281597,117.499375,5.574306,1000.713194,0.001389,0.000417,31.575625,31.884375
364,2022-10-29,159.893264,43.795764,123.982986,167.424722,162.734792,26.248333,91.560972,0.378264,0.651111,0.183750,86.063264,2.962153,999.457639,0.001389,0.000000,32.243681,32.270139
365,2022-10-30,0.000000,0.000000,0.000000,0.000000,0.000000,23.900000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000.000000,0.000000,0.000000,24.100000,24.400000